name: Java Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Java 8 on the agent
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    # Compile your application with Maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
